#!/usr/bin/env python3

"""
Module that performs extraction. For usage, refer to documentation for the class
'Extractor'. This module can also be executed directly,
e.g. 'extractor.py <input> <output>'.
"""

import os
import sys
import hashlib
import logging
import shutil
import tempfile
import traceback
from stat import S_ISREG
from subprocess import call, DEVNULL, CalledProcessError


class Extractor:
    """
    This extractor first use binwalk to recursively extract all files from the firmware,
    and identify rootfs from the extracted files.
    """

    # This is generated by copilot
    ROOTFS_DIRS = [
        "squashfs-root",
        "jffs2-root",
        "romfs-root",
        "ubi-root",
        "ubifs-root",
        "yaffs2-root",
        "yaffs-root",
        "ext2-root",
        "ext3-root",
        "ext4-root",
        "vfat-root",
        "ntfs-root",
        "f2fs-root",
        "btrfs-root",
        "jffs-root",
        "cramfs-root",
        "minix-root",
        "hfs-root",
        "hfsplus-root",
    ]

    UNIX_DIRS = [
        "bin",
        "etc",
        "dev",
        "home",
        "lib",
        "mnt",
        "opt",
        "root",
        "run",
        "sbin",
        "tmp",
        "usr",
        "var",
        "www",
        "proc",
    ]

    UNIX_THRESHOLD = 2

    def __init__(self, verbose=logging.INFO):
        self.logger = logging.getLogger(__name__)
        self.logger.addHandler(logging.StreamHandler())
        self.logger.setLevel(verbose)

        if self.logger.level != logging.DEBUG:
            self.call_stdout = DEVNULL
            self.call_stderr = DEVNULL
        else:
            self.call_stdout = None
            self.call_stderr = None

    def extract(self, inpath, outpath):
        """
        Perform extraction of firmware updates from input to tarballs in output
        directory using a thread pool.
        """

        if not os.path.isfile(inpath):
            self.logger.info("!! Cannot read file: %s", inpath)
            return False

        if os.geteuid() == 0:
            acquire_root = ""
        elif shutil.which("fakeroot"):
            acquire_root = "fakeroot"
        elif shutil.which("sudo"):
            acquire_root = "sudo"
        else:
            acquire_root = None

        return self.do_extract(inpath, outpath, acquire_root)

    @classmethod
    def io_find_rootfs(cls, start):
        """
        Attempts to find a Linux root directory.
        """

        # Recurse into single directory chains, e.g. jffs2-root/fs_1/.../
        found = False
        possible_roots = []
        for root, dirs, _ in os.walk(start):
            if possible_roots and any(
                root.startswith(dir + os.path.sep) for dir in possible_roots
            ):
                continue
            count = 0
            for d in dirs:
                if d in cls.UNIX_DIRS:
                    count += 1
            if count >= cls.UNIX_THRESHOLD:
                found = True
                possible_roots.append(root)

            # judge by the directory name
            elif os.path.basename(root) in cls.ROOTFS_DIRS and count:
                found = True
                possible_roots.append(root)

        return found, possible_roots

    def do_extract(self, inpath, outpath, acquire_root):
        """
        Perform the actual extraction of firmware updates, recursively. Returns
        True if extraction complete, otherwise False.

        :param acquire_root: command to acquire root privilege if it is None, do not acquire root privilege
        """

        temp_dir = tempfile.mkdtemp()

        try:
            self.logger.info(">> Inpp: %s", os.path.basename(inpath))
            self.logger.info(">> Outp: %s", os.path.basename(outpath))
            self.logger.info(">> Temp: %s", temp_dir)

            os.chdir(temp_dir)
            files_to_extract = self.try_unzip(inpath, temp_dir)
            if not files_to_extract:
                files_to_extract = [inpath]
            self.logger.info(">> Extracting %s", files_to_extract)
            for file_to_extract in files_to_extract:
                run_as = "--run-as root " if acquire_root is not None else ""
                try:
                    call(
                        f"timeout 600 {acquire_root} binwalk {run_as} -Me --preserve-symlinks '{file_to_extract}'",
                        shell=True,
                        stdout=self.call_stdout,
                        stderr=self.call_stderr,
                    )
                except CalledProcessError:
                    self.logger.info(
                        ">> Binwalk fails to extract '%s'", file_to_extract
                    )
            self.logger.info(">> Chmoding %s", temp_dir)
            try:
                call(
                    f"chmod -R 755 {temp_dir}",
                    shell=True,
                    stdout=self.call_stdout,
                    stderr=self.call_stderr,
                )
            except CalledProcessError:
                self.logger.info(">> chmod error on '%s'", temp_dir)

            self.logger.info(">> Finding rootfs")
            fs_found, old_fs_paths = Extractor.io_find_rootfs(temp_dir)
            fs_paths = [item for item in old_fs_paths if("cpio-root" not in item)]
            
            self.logger.info(fs_paths)
            if fs_found:
                if len(fs_paths) == 1:
                    fs_path = fs_paths[0]
                else:
                    # merge rootfs
                    os.mkdir("merged_rootfs")
                    fs_path = "merged_rootfs"
                    for path in fs_paths:
                        ExtractorUtils.copytree(path, fs_path, symlinks=True)

                min_sz = 1024 * 1024
                if ExtractorUtils.get_dir_size(fs_path, min_sz) < min_sz:
                    self.logger.info(">> Filesystem is too small in %s", fs_paths)

                self.logger.info(">> Found Linux filesystem in %s", fs_paths)

                os.makedirs(os.path.dirname(outpath), exist_ok=True)
                if os.path.exists(outpath):
                    os.remove(outpath)

                tmp_archive = os.path.join(temp_dir, "extracted_fs")
                shutil.make_archive(tmp_archive, "tar", root_dir=fs_path)
                shutil.move(tmp_archive + ".tar", outpath)

                return True
        except KeyboardInterrupt:
            self.logger.info(">> Extraction interrupted")
        except Exception:  # pylint: disable=broad-except
            traceback.print_exc()
        finally:
            shutil.rmtree(temp_dir)

        return False

    def try_unzip(self, target_path, temp_dir):
        """Try to unzip the file.

        :return: the files to be further extracted
        """
        if not target_path.lower().endswith(".zip"):
            return []
        self.logger.info(">> Try unzip %s", target_path)
        try:
            call(
                f"unzip {target_path}",
                shell=True,
                stdout=self.call_stdout,
                stderr=self.call_stderr,
            )
        except CalledProcessError:
            self.logger.info(">> Unzip fail for %s", target_path)
            return []
        results = []
        # Traverse unzipped files
        for root, _, files in os.walk(temp_dir):
            for file in files:
                if os.path.basename(target_path) == file:
                    continue
                results.append(os.path.join(root, file))
        return results

    def unpack(self, inptar: str, outdir: str, use_chroot=False):
        """Unpack a tarball to a directory.
        
        :param inptar: the tarball to unpack
        :param outdir: the output directory
        :param use_chroot: whether to use chroot if available
        """

        self.logger.info(">> Unpacking %s to %s", inptar, outdir)

        if not os.path.isfile(inptar):
            self.logger.info("!! Cannot read file: %s", inptar)
            return False

        if os.path.isdir(outdir):
            self.logger.info(">> Removing existing output directory %s", outdir)
            shutil.rmtree(outdir)
        os.makedirs(outdir, exist_ok=True)

        extra_tar_args = ["--no-same-permissions", "--keep-directory-symlink"]
        # First try to use chroot
        chroot_ok = use_chroot
        if shutil.which("chroot") and use_chroot:
            cmd = [
                "chroot",
                outdir,
                "/tar",
                "-x",
                "-f",
                "./archive.tar",
            ] + extra_tar_args
            if os.geteuid() == 0:
                pass
            elif shutil.which("fakechroot"):
                if shutil.which("fakeroot"):
                    cmd = ["fakechroot", "fakeroot"] + cmd
                else:
                    cmd = ["fakechroot"] + cmd
            elif shutil.which("sudo"):
                cmd = ["sudo"] + cmd
            else:
                chroot_ok = False

        if chroot_ok:
            # link the required commands
            util_paths = []
            for util in ["tar", "ls", "rm", "chmod"]:
                bin_path = shutil.which(util)
                if not bin_path:
                    chroot_ok = False
                    break
                util_paths.append(bin_path)
            else:
                for util_path in util_paths:
                    os.symlink(
                        util_path, os.path.join(outdir, os.path.basename(util_path))
                    )
                os.symlink(os.path.abspath(inptar), os.path.join(outdir, "archive.tar"))

        # If chroot is not available, use tar directly
        if not chroot_ok:
            cmd = ["tar", "-x", "-f", inptar, "-C", outdir] + extra_tar_args

        success = True
        try:
            self.logger.info(">> Run command %s", " ".join(cmd))
            call(cmd, stdout=self.call_stdout, stderr=self.call_stderr, cwd=outdir)
            if chroot_ok:
                success = len(os.listdir(outdir)) > len(util_paths) + 1
        except CalledProcessError:
            success = False

        if chroot_ok:
            # Remove symbolic links
            for util_path in util_paths:
                os.unlink(os.path.join(outdir, os.path.basename(util_path)))
            os.unlink(os.path.join(outdir, "archive.tar"))

        if not success:
            self.logger.info("!! Failed to unpack %s to %s", inptar, outdir)
            shutil.rmtree(outdir)

        return success


class ExtractorUtils:
    """Utility class for extraction."""

    @staticmethod
    def io_md5(target):
        """
        Performs MD5 with a block size of 64kb.
        """
        blocksize = 65536
        hasher = hashlib.md5()

        stat = os.stat(target)
        if not S_ISREG(stat.st_mode):
            hasher.update(target.encode("utf-8"))
        else:
            with open(target, "rb") as ifp:
                buf = ifp.read(blocksize)
                while buf:
                    hasher.update(buf)
                    buf = ifp.read(blocksize)
        return hasher.hexdigest()

    @staticmethod
    def copytree(src, dst, symlinks=False, ignore=None):
        """Copy a directory tree recursively."""
        for item in os.listdir(src):
            s = os.path.join(src, item)
            d = os.path.join(dst, item)
            try:
                if os.path.islink(s):
                    # Only reserve the symbolic link
                    if symlinks:
                        if os.path.lexists(d):
                            os.unlink(d)
                        os.symlink(os.readlink(s), d)
                elif os.path.isdir(s):
                    # dirs_exist_ok is only available after Python 3.8
                    # shutil.copytree(s, d, symlinks, ignore, dirs_exist_ok=True)
                    if not os.path.exists(d):
                        try:
                            shutil.copytree(s, d, symlinks, ignore)
                        except FileExistsError:
                            pass
                    else:
                        # merge the directory
                        ExtractorUtils.copytree(s, d, symlinks, ignore)
                else:
                    if not os.path.isfile(s):
                        continue
                    try:
                        shutil.copy2(s, d)
                    except PermissionError:
                        pass
            except shutil.Error:
                continue

    @staticmethod
    def get_dir_size(path, stop_at=None):
        """Get the size of a directory recursively."""
        total = 0
        with os.scandir(path) as it:
            for entry in it:
                if entry.is_file():
                    total += entry.stat().st_size
                elif entry.is_dir():
                    total += ExtractorUtils.get_dir_size(entry.path)
                if stop_at and total >= stop_at:
                    return total
        return total


def _main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input> <output>")
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]
    extractor = Extractor()
    extractor.extract(input_path, output_path)


if __name__ == "__main__":
    _main()
